package main

import (
	"embed"
	"fmt"
	"io/fs"
	"log"
	"net/http"
	"strings"

	"caddyadmin/auth"
	"caddyadmin/caddy"
	"caddyadmin/config"
	"caddyadmin/database"
	"caddyadmin/handlers"
	"caddyadmin/middleware"
	"caddyadmin/models"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "caddyadmin/docs" // Docs generated by Swag CLI
)

// @title           Caddy Proxy Manager API
// @version         1.0
// @description     API server for Caddy Proxy Manager
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.email  support@example.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
// @name Authorization
//go:embed static/*
var staticFS embed.FS

func main() {
	// Load configuration
	cfg := config.Load()

	// Initialize authentication
	auth.Initialize(cfg)

	// Initialize database
	if err := database.Initialize(cfg.DatabasePath); err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}

	// Create Caddy client
	caddyClient := caddy.NewClient(cfg.CaddyAPIURL)

	// Sync database state to Caddy on startup (restore after Caddy restart)
	if err := syncDatabaseToCaddy(caddyClient); err != nil {
		log.Printf("⚠️  Config sync failed: %v (manual sync available at POST /api/config/sync)", err)
	}

	// Create Gin router (release mode for cleaner logs)
	gin.SetMode(gin.ReleaseMode)
	r := gin.Default()

	// Setup middleware
	middleware.SetupMiddleware(r)

	// Create handlers
	healthHandler := handlers.NewHealthHandler(caddyClient)
	siteHandler := handlers.NewSiteHandler(caddyClient)
	routeHandler := handlers.NewRouteHandler(caddyClient)
	upstreamHandler := handlers.NewUpstreamHandler(caddyClient)
	configHandler := handlers.NewConfigHandler(caddyClient)
	historyHandler := handlers.NewHistoryHandler(caddyClient)
	tlsHandler := handlers.NewTLSHandler(caddyClient)
	certificateHandler := handlers.NewCertificateHandler("./storage/certificates")
	middlewareHandler := handlers.NewMiddlewareHandler()
	authHandler := handlers.NewAuthHandler()

	// API routes
	api := r.Group("/api")
	{
		// Swagger Documentation
		api.GET("/docs/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

		// Health endpoints
		api.GET("/health", healthHandler.Health)

		// Auth endpoints (public - no auth required)
		api.POST("/auth/login", authHandler.Login)
		
		// Protected auth endpoints
		protectedAuth := api.Group("/auth")
		protectedAuth.Use(auth.AuthMiddleware())
		{
			protectedAuth.GET("/me", authHandler.GetCurrentUser)
			protectedAuth.POST("/logout", authHandler.Logout)
		}

		api.GET("/ready", healthHandler.Ready)
		api.GET("/live", healthHandler.Live)

		// Backup endpoints
		backupHandler := handlers.NewBackupHandler()
		api.GET("/backup", backupHandler.CreateBackup)
		api.GET("/backup/download", backupHandler.DownloadBackupFile)
		api.POST("/backup/restore", backupHandler.RestoreBackup)
		api.POST("/backup/upload", backupHandler.UploadRestore)

		// Metrics endpoints
		metricsHandler := handlers.NewMetricsHandler()
		api.GET("/metrics", metricsHandler.GetMetrics)
		api.GET("/metrics/prometheus", metricsHandler.GetPrometheusMetrics)

		// Caddy metrics (live from Caddy server)
		caddyMetricsHandler := handlers.NewCaddyMetricsHandler(caddyClient)
		api.GET("/caddy/metrics", caddyMetricsHandler.GetCaddyMetrics)

		// Logs endpoints
		logsHandler := handlers.NewLogsHandler(caddyClient)
		api.GET("/logs", logsHandler.GetLogs)
		api.GET("/logs/stream", logsHandler.StreamLogs)
		api.GET("/logs/access", logsHandler.GetAccessLogs)
		api.POST("/caddyfile/validate", logsHandler.ValidateCaddyfile)

		// SSE endpoints (protected)
		sseHandler := handlers.NewSSEHandler()
		events := api.Group("/events")
		events.Use(auth.AuthMiddleware())
		{
			events.GET("/stream", sseHandler.Stream)
			events.GET("/status", sseHandler.GetStatus)
		}

		// Site endpoints
		api.GET("/sites", siteHandler.ListSites)
		api.POST("/sites", siteHandler.CreateSite)
		api.GET("/sites/:id", siteHandler.GetSite)
		api.PUT("/sites/:id", siteHandler.UpdateSite)
		api.DELETE("/sites/:id", siteHandler.DeleteSite)

		// Route endpoints (nested under sites)
		api.GET("/sites/:id/routes", routeHandler.ListRoutes)
		api.POST("/sites/:id/routes", routeHandler.CreateRoute)
		api.GET("/routes/:id", routeHandler.GetRoute)
		api.PUT("/routes/:id", routeHandler.UpdateRoute)
		api.DELETE("/routes/:id", routeHandler.DeleteRoute)

		// TLS endpoints (nested under sites)
		api.GET("/sites/:id/tls", tlsHandler.GetTLSConfig)
		api.PUT("/sites/:id/tls", tlsHandler.UpdateTLSConfig)

		// Middleware endpoints (nested under sites)
		api.GET("/sites/:id/middleware", middlewareHandler.GetMiddlewareSettings)
		api.PUT("/sites/:id/middleware", middlewareHandler.UpdateMiddlewareSettings)
		
		// Basic auth users (for sites)
		api.GET("/sites/:id/auth/users", middlewareHandler.ListBasicAuthUsers)
		api.POST("/sites/:id/auth/users", middlewareHandler.CreateBasicAuthUser)
		api.DELETE("/sites/:id/auth/users/:userId", middlewareHandler.DeleteBasicAuthUser)
		
		// Header rules
		api.GET("/sites/:id/headers", middlewareHandler.ListHeaderRules)
		api.POST("/sites/:id/headers", middlewareHandler.CreateHeaderRule)
		api.DELETE("/headers/:id", middlewareHandler.DeleteHeaderRule)
		
		// Access rules
		api.GET("/sites/:id/access", middlewareHandler.ListAccessRules)
		api.POST("/sites/:id/access", middlewareHandler.CreateAccessRule)
		api.DELETE("/access/:id", middlewareHandler.DeleteAccessRule)
		
		// Rewrite rules
		api.GET("/sites/:id/rewrites", middlewareHandler.ListRewriteRules)
		api.POST("/sites/:id/rewrites", middlewareHandler.CreateRewriteRule)
		api.DELETE("/rewrites/:id", middlewareHandler.DeleteRewriteRule)

		// Redirect rules
		api.GET("/sites/:id/redirects", middlewareHandler.ListRedirectRules)
		api.POST("/sites/:id/redirects", middlewareHandler.CreateRedirectRule)
		api.DELETE("/redirects/:id", middlewareHandler.DeleteRedirectRule)

		// Upstream endpoints
		api.GET("/upstreams", upstreamHandler.ListUpstreams)
		api.POST("/upstreams", upstreamHandler.CreateUpstream)
		api.GET("/upstreams/:id", upstreamHandler.GetUpstream)
		api.PUT("/upstreams/:id", upstreamHandler.UpdateUpstream)
		api.DELETE("/upstreams/:id", upstreamHandler.DeleteUpstream)
		api.GET("/upstreams/status", upstreamHandler.GetUpstreamStatus)

		// Upstream group endpoints
		api.GET("/upstream-groups", upstreamHandler.ListUpstreamGroups)
		api.POST("/upstream-groups", upstreamHandler.CreateUpstreamGroup)
		api.GET("/upstream-groups/:id", upstreamHandler.GetUpstreamGroup)
		api.PUT("/upstream-groups/:id", upstreamHandler.UpdateUpstreamGroup)
		api.DELETE("/upstream-groups/:id", upstreamHandler.DeleteUpstreamGroup)

		// Config endpoints
		api.GET("/config", configHandler.GetCaddyConfig)
		api.POST("/config", configHandler.LoadCaddyConfig)
		api.POST("/config/sync", configHandler.SyncConfig)
		api.POST("/config/adapt", configHandler.AdaptConfig)
		api.POST("/config/stop", configHandler.StopCaddy)
		api.GET("/config/path/*path", configHandler.GetCaddyConfigPath)
		api.POST("/config/path/*path", configHandler.SetCaddyConfigPath)
		api.DELETE("/config/path/*path", configHandler.DeleteCaddyConfigPath)

		// Global settings
		api.GET("/settings", configHandler.GetGlobalSettings)
		api.PUT("/settings", configHandler.UpdateGlobalSettings)

		// History endpoints
		api.GET("/history", historyHandler.ListHistory)
		api.GET("/history/compare", historyHandler.CompareHistory)
		api.GET("/history/:id", historyHandler.GetHistoryEntry)
		api.POST("/history/:id/rollback", historyHandler.RollbackToHistory)

		// PKI endpoints
		api.GET("/pki/ca/:id", tlsHandler.GetPKICA)
		api.GET("/pki/ca/:id/certificates", tlsHandler.GetPKICACertificates)

		// Custom Certificate endpoints
		api.GET("/certificates", certificateHandler.GetCertificates)
		api.GET("/certificates/:id", certificateHandler.GetCertificate)
		api.POST("/certificates", certificateHandler.UploadCertificate)
		api.DELETE("/certificates/:id", certificateHandler.DeleteCertificate)
	}

	// Serve Static Frontend (SPA)
	if cfg.Environment == "production" {
		// Extract the subdirectory "static" from the embedded FS
		fSys, err := fs.Sub(staticFS, "static")
		if err != nil {
			log.Fatalf("Failed to embed static files: %v", err)
		}

		// Serve static files
		r.Use(func(c *gin.Context) {
			path := c.Request.URL.Path
			// Skip API routes
			if strings.HasPrefix(path, "/api") {
				c.Next()
				return
			}

			// Check if file exists in static FS
			// Clean path to prevent directory traversal
			cleanPath := strings.TrimPrefix(path, "/")
			if cleanPath == "" {
				cleanPath = "index.html"
			}

			if _, err := fSys.Open(cleanPath); err == nil {
				c.FileFromFS(cleanPath, http.FS(fSys))
				c.Abort()
				return
			}

			// Fallback to index.html for SPA routing
			// But only for non-API routes and if we accept text/html
			if !strings.HasPrefix(path, "/api") {
				c.FileFromFS("index.html", http.FS(fSys))
				c.Abort()
				return
			}
		})
	}

	// Start server
	addr := fmt.Sprintf(":%s", cfg.ServerPort)
	log.Printf("Starting Caddy Admin API on %s", addr)
	log.Printf("Caddy Admin API: %s", cfg.CaddyAPIURL)
	if err := r.Run(addr); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}

// syncDatabaseToCaddy syncs all database configuration to Caddy on startup
func syncDatabaseToCaddy(client *caddy.Client) error {
	configBuilder := caddy.NewConfigBuilder(client)

	// Get all sites
	var sites []models.Site
	if err := database.GetDB().Where("enabled = ?", true).Find(&sites).Error; err != nil {
		return fmt.Errorf("failed to load sites: %w", err)
	}

	// Get routes for each site
	routesMap := make(map[string][]models.Route)
	for _, site := range sites {
		var routes []models.Route
		database.GetDB().Where("site_id = ? AND enabled = ?", site.ID, true).Order("`order` ASC").Find(&routes)
		routesMap[site.ID] = routes
	}

	// Get redirect rules
	redirectsMap := make(map[string][]models.RedirectRule)
	for _, site := range sites {
		var rules []models.RedirectRule
		database.GetDB().Where("site_id = ? AND enabled = ?", site.ID, true).Order("priority DESC, created_at DESC").Find(&rules)
		redirectsMap[site.ID] = rules
	}

	// Get upstream groups
	var upstreamGroups []models.UpstreamGroup
	database.GetDB().Find(&upstreamGroups)
	groupsMap := make(map[string]*models.UpstreamGroup)
	upstreamsMap := make(map[string][]models.Upstream)
	for i := range upstreamGroups {
		groupsMap[upstreamGroups[i].Name] = &upstreamGroups[i]
		var upstreams []models.Upstream
		database.GetDB().Model(&upstreamGroups[i]).Association("Upstreams").Find(&upstreams)
		upstreamsMap[upstreamGroups[i].Name] = upstreams
	}

	// Get global settings
	var settings models.GlobalSettings
	database.GetDB().First(&settings)

	// Get custom certificates
	var certificates []models.CustomCertificate
	database.GetDB().Find(&certificates)

	// Build configuration
	config, err := configBuilder.BuildFullConfig(sites, routesMap, redirectsMap, groupsMap, upstreamsMap, certificates, &settings)
	if err != nil {
		return fmt.Errorf("failed to build config: %w", err)
	}

	// Apply to Caddy
	if err := configBuilder.ApplyConfig(config); err != nil {
		return fmt.Errorf("failed to apply config: %w", err)
	}

	log.Printf("✅ Synced %d sites to Caddy", len(sites))
	return nil
}
